#coding=UTF-8
CSRF_ENABLED = True
SECRET_KEY = 'dontcare'

SENTRY_DSN = ''

SECURITY_URL_PREFIX = '/auth'

SECURITY_REGISTERABLE = False
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_SEND_PASSWORD_CHANGE_EMAIL = False
SECURITY_SEND_PASSWORD_RESET_NOTICE_EMAIL = False
SECURITY_USER_IDENTITY_ATTRIBUTES = ['ra']
