"""aluno roles

Revision ID: 47e2b7da19b1
Revises: 4d48918562d
Create Date: 2015-10-27 21:06:07.097495

"""

# revision identifiers, used by Alembic.
revision = '47e2b7da19b1'
down_revision = '4d48918562d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_alunos',
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.add_column(u'aluno', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column(u'aluno', sa.Column('email', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'aluno', 'email')
    op.drop_column(u'aluno', 'active')
    op.drop_table('roles_alunos')
    op.drop_table('role')
    ### end Alembic commands ###
