"""aluno e palestra

Revision ID: 4d48918562d
Revises: None
Create Date: 2015-10-20 22:20:21.231152

"""

# revision identifiers, used by Alembic.
revision = '4d48918562d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ra', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('palestra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trilha', sa.String(length=255), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('bio_autor', sa.Text(), nullable=True),
    sa.Column('autor', sa.String(length=255), nullable=True),
    sa.Column('dia', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('palestra_aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palestra_id', sa.Integer(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['palestra_id'], ['palestra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('palestra_aluno')
    op.drop_table('palestra')
    op.drop_table('aluno')
    ### end Alembic commands ###
